APP_NAME = "JARVIS"
VERSION = "0.1.0"
AUTHOR = "Paban Rai"
OLLAMA_MODEL = "qwen3:4b"
TIMEOUT = 30

# === NEW NETWORK INFRASTRUCTURE CONFIGURATIONS ===
NETWORK_HOST = "8.8.8.8"
NETWORK_PORT = 53
NETWORK_TIMEOUT = 3
OLLAMA_API_URL = "http://localhost:11434/api/tags"